AC-1080: Appointment Scheduling Integration
openmrs/openmrs-contrib-android-client pull request #1000
Opened 2023-06-17 22:33 UTC by shubhamsgit

## Description of what I changed

- This is the start of Appointment Scheduling functionality in the SDK

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-1080

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2023-06-26 16:18 UTC, rishabh-997 requested changes

2023-06-26 16:18 UTC, rishabh-997 commented on .idea/runConfigurations.xml
> -<?xml version="1.0" encoding="UTF-8"?>
Undo changes that are not relevant

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/TimeSlot.kt
> +    @Expose var appointmentBlock: AppointmentBlock? = null,
```suggestion
    @Expose
    var appointmentBlock: AppointmentBlock? = null,
```

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/ProviderSchedule.kt
> +package com.openmrs.android_sdk.library.models
copywright

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/Appointment.kt
> +    @Expose var timeSlot: TimeSlot? = null,
```suggestion
    @Expose 
    var timeSlot: TimeSlot? = null,
```

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/StringListConverter.kt
> +
just one is enough

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/StringListConverter.kt
> +package com.openmrs.android_sdk.library.databases
copywright

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
> +        for(type in blockTypesObjectList!!){
```suggestion
        val blockTypesObjectList = appointmentBlock?.types // List received from server
        val typeStringList = mutableListOf<String>() // Entity requires this list
        for (type in blockTypesObjectList!!) { 
```

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/AppointmentRoomDAO.kt
> +package com.openmrs.android_sdk.library.dao
copywright

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/AppointmentRoomDAO.kt
> +import androidx.room.*
stars

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepository.kt
> +class AppointmentRepository @Inject constructor() : BaseRepository(){
```suggestion
class AppointmentRepository @Inject constructor() : BaseRepository() {
```

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepository.kt
> +        )
```suggestion
        })
```

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepository.kt
> +    fun createTimeSlot(timeSlot: TimeSlot): Observable<TimeSlot>{
Add spacing in all remaining functions

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepository.kt
> +        )
```suggestion
        }
        )
```
```suggestion
        })
```
Add this change in all remaining functions

2023-06-26 16:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepository.kt
> +            }
You can create a function instead of repeating the same lines

2023-06-28 19:15 UTC, shubhamsgit commented on .idea/runConfigurations.xml
revert the changes. Please ignore this. It's the same file as before.

2023-06-28 19:59 UTC, shubhamsgit commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/AppointmentRoomDAO.kt
> +package com.openmrs.android_sdk.library.dao
My bad! I keep forgetting this :P

2023-06-28 20:58 UTC, shubhamsgit commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepository.kt
> +            }
Indeed! Update the PR by creating a function using Generics

2023-06-28 20:59 UTC, shubhamsgit commented
Pushed the requested changes. Please have a look now :)

2023-06-29 04:30 UTC, rishabh-997 approved these changes

2023-06-29 04:30 UTC, merged