AC:1082: Orders Feature for SDK
openmrs/openmrs-contrib-android-client pull request #1002
Opened 2023-07-08 21:14 UTC by shubhamsgit

## Description of what I changed

- This is the start of the new feature for the SDK.
- This feature enables the implementers to interact with the "Orders" endpoint of the OpenMRS through the SDK

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-1082

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2023-07-20 02:32 UTC, rishabh-997 requested changes

2023-07-20 02:32 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/OrderRepository.kt
> +            }
Create a helper function instead of code repetition

2023-07-20 02:32 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/OrderRepository.kt
> +import com.openmrs.android_sdk.library.models.*
Avoid star imports

2023-07-20 02:32 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/OrderRoomDAO.kt
> +import androidx.room.*
avoid star imports

2023-07-20 02:32 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
> +    fun convert(orderGet: OrderGet): OrderEntity {
pls add params and return information in comments

2023-07-20 02:32 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
> +        orderEntity.autoExpireDate = orderGet.autoExpireDate
Pls look if it is possible to reduce code lines by using for loop... Something like
`for keys, values in orderGet:
orderEntity["key"]=value
`

2023-07-29 19:35 UTC, shubhamsgit commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
> +        orderEntity.autoExpireDate = orderGet.autoExpireDate
@rishabh-997 I used Kotlin's "apply" to somewhat reduce the code

2023-07-31 19:11 UTC, rishabh-997 approved these changes

2023-07-31 19:11 UTC, merged