Fixed the orientaion in the layout
openmrs/openmrs-contrib-android-client pull request #814
Opened 2020-09-21 09:18 UTC by sachin-0102

## Description of what I changed
Fixed the orientation of dashboard layout and alignment of text

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-734

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x ] All new and existing **tests passed**.

- [ x] My pull request is **based on the latest changes** of the master branch.

2020-09-21 13:00 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
>      <TableLayout
@sachin-0102 It's preferred to use [ConstraintLayout](https://developer.android.com/reference/android/support/constraint/ConstraintLayout) from now onwards because the layout can be flattened (not having nested layouts) so it's more efficient, and you can design it visually in Android Studio.

2020-09-21 13:01 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
> +                    android:layout_width="180dp"
Don't fix the width size... Use Constraint layout to adjust constraints

2020-09-21 13:02 UTC, rishabh-997 requested changes
Fix the PR with the changes and they apply to all other card views... Also, claim the task on JIRA first.

2020-09-21 13:24 UTC, sachin-0102 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
> +                    android:layout_width="180dp"
Okay I'll adjust it sir

2020-09-21 13:25 UTC, sachin-0102 commented
> Fix the PR with the changes and they apply to all other card views... Also, claim the task on JIRA first.

2020-09-21 14:37 UTC, sachin-0102 commented
@rishabh-997 sir please have a look, I've made the required chnages

2020-09-21 15:25 UTC, rishabh-997 commented on .idea/render.experimental.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Why is this file required?

2020-09-21 15:26 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/row_similar_patient.xml
> +        android:id="@+id/cardView1"
Explain this change

2020-09-21 15:27 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
>          android:stretchColumns="1">
What is the use of `android:stretchColumns` here?

2020-09-21 15:29 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
> +                    android:id="@+id/FormsLabel"
use camelCase to name view ids.

2020-09-21 15:29 UTC, sachin-0102 commented on openmrs-client/src/main/res/layout/row_similar_patient.xml
> +        android:id="@+id/cardView1"
> Explain this change

When I changed the table layout to constraint layout, the ids changed to cardView5 , cardView6 etc... So I renumbered them from 1 to 5

2020-09-21 15:30 UTC, rishabh-997 requested changes
Explain or revert the above queries

2020-09-21 15:31 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/row_similar_patient.xml
> +        android:id="@+id/cardView1"
Is this the correct file?

2020-09-21 15:34 UTC, sachin-0102 commented on .idea/render.experimental.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file was auto created on changing the table layout to constraint layout

2020-09-21 15:36 UTC, sachin-0102 commented on openmrs-client/src/main/res/layout/row_similar_patient.xml
> +        android:id="@+id/cardView1"
The ids were changed in the entire app when I changed the table layout
So I though it would be best to convert it back in the entire app

2020-09-21 15:37 UTC, sachin-0102 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
>          android:stretchColumns="1">
> Explain or revert the above queries

On it

2020-09-21 15:40 UTC, sachin-0102 commented on openmrs-client/src/main/res/layout/row_similar_patient.xml
> +        android:id="@+id/cardView1"
I'll change it back

2020-09-21 15:57 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
> +            android:id="@+id/cardView"
@LuGO0, do you think we should name it to something more meaningful?

2020-09-21 16:13 UTC, LuGO0 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
> +            android:id="@+id/cardView"
@rishabh-997  we can make it more descriptive .

2020-09-21 16:16 UTC, LuGO0 commented
@sachin-0102 The issue is still not claimed,
Follow the Guidelines before starting to contribute read about how to make a PR and the JIRA workflow !!

2020-09-21 16:16 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
> +            android:id="@+id/cardView"
Rename all 5 card views to functionCardView. Ex `findPatientCardView`

2020-09-21 16:18 UTC, sachin-0102 commented
> @sachin-0102 The issue is still not claimed,
> Follow the Guidelines before starting to contribute read about how to make a PR and the JIRA workflow !!

Yes sir. The last comment on the issue said that anyone could take that up so I made a PR, I'll keep that in mind from next time.

2020-09-21 16:18 UTC, sachin-0102 commented on openmrs-client/src/main/res/layout/fragment_dashboard.xml
> +            android:id="@+id/cardView"
Okay sir I'll do it.

2020-09-21 17:36 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/row_similar_patient.xml
> +        android:id="@+id/findPatientsCardView"
make it patientCardView

2020-09-21 17:38 UTC, rishabh-997 requested changes
Read the PR tips carefully... You still lack two changes before I merge it... Ill leave that to you to explore :)

2020-09-21 18:46 UTC, sachin-0102 commented on openmrs-client/src/main/res/layout/row_similar_patient.xml
> +        android:id="@+id/findPatientsCardView"
Done sir

2020-09-21 18:50 UTC, rishabh-997 approved these changes
Nice Work. Follow the instructions carefully next time. Keep contributing, thanks :)

2020-09-21 18:51 UTC, merged

2020-09-21 18:53 UTC, sachin-0102 commented
For sure @rishabh-997 sir. Thank you for your guidance.

2021-01-06 18:33 UTC, MasterBlaster99 commented
> Fix the PR with the changes and they apply to all other card views... Also, claim the task on JIRA first.

sir, the claim issue button on jira issue tracker is not there how should i claim on an issue ?