AC-834 Migrate room Entity classes to Kotlin
openmrs/openmrs-contrib-android-client pull request #816
Opened 2020-09-27 09:48 UTC by prayutsu

## Description of what I changed

1. Converted Entities Java code into Kotlin
2. After converting the files into Kotlin, various files had automatically changed some piece of code, the original state of the files was restored.
3. Broken tests due to the change were fixed

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-834

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2020-09-27 11:14 UTC, prayutsu commented
@rishabh-997 Please take a look

2020-09-28 06:13 UTC, LuGO0 commented
@prayutsu good work add licence text at the starting of each file .

2020-09-28 06:16 UTC, LuGO0 requested changes

2020-09-28 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/EncounterEntity.kt
> +
here add the licence text !!

2020-09-28 06:16 UTC, prayutsu commented
> @prayutsu good work, add licence text at the starting of each file .

What exactly is licence text and where can I get it?
Can I find that in the files in the deleted files?

2020-09-28 08:20 UTC, rishabh-997 commented
> > @prayutsu good work, add licence text at the starting of each file .
> 
> What exactly is licence text and where can I get it?
> Can I find that in the deleted files?

you can find them in any java file at the top... right above the package

2020-09-28 08:57 UTC, prayutsu commented
@rishabh-997 Just want to confirm again, the files that I have updated didn't contain licence text earlier, also other entity class that was already in Kotlin don't have any licence text, so should I still add that?

2020-09-28 09:06 UTC, rishabh-997 commented
> also other entity class that was already in Kotlin don't have any licence text

Are you sure??? 
1. [AllergyEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/AllergyEntity.kt#L1)
2. [ConceptEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/ConceptEntity.kt#L1)
3. [FormResourceEntity.ky](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/FormResourceEntity.kt#L1)
4. [LocationEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/LocationEntity.kt#L1)
5. [ProviderEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/models/Provider.kt#L1)
6. [VisitEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/models/Visit.kt#L1)

2020-09-28 09:25 UTC, prayutsu commented
> > also other entity class that was already in Kotlin don't have any licence text
> 
> Are you sure???
> 
> 1. [AllergyEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/AllergyEntity.kt#L1)
> 2. [ConceptEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/ConceptEntity.kt#L1)
> 3. [FormResourceEntity.ky](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/FormResourceEntity.kt#L1)
> 4. [LocationEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/LocationEntity.kt#L1)
> 5. [ProviderEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/models/Provider.kt#L1)
> 6. [VisitEntity.kt](https://github.com/openmrs/openmrs-contrib-android-client/blob/47529781e09f5fc7e76fbdf5f19ad9470658e065/openmrs-client/src/main/java/org/openmrs/mobile/models/Visit.kt#L1)

Ah, I just looked at the files I edited myself, thanks @rishabh-997

2020-09-28 09:27 UTC, prayutsu commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/EncounterEntity.kt
> +
Done

2020-09-28 09:28 UTC, prayutsu commented
@LuGO0 @rishabh-997 Implemented reviewed changes successfully, please take a look

2020-09-28 21:01 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/EncounterEntity.kt
> +    @Expose
Why are you using `@SerializedName` and `@Expose` annotations... This file has nothing to do with retrofit calls as far as I remember... Any specific reason???

2020-09-28 21:03 UTC, rishabh-997 requested changes
Since this PR involves a change in the schema, therefore I will need to check it thoroughly...

2020-09-28 21:04 UTC, rishabh-997 commented
> Since this PR involves a change in the schema, therefore I will need to check it thoroughly... I will post any NPE encountered here...

2020-09-29 05:36 UTC, prayutsu commented
> Since this PR involves a change in the schema, therefore I will need to check it thoroughly... I will post any NPE encountered here...

Sure

2020-09-29 07:50 UTC, prayutsu commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/EncounterEntity.kt
> +    @Expose
Okay, I'll remove it. So, this should be removed from this file only or other 3 files too?

2020-09-29 18:20 UTC, LuGO0 requested changes

2020-09-29 18:20 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.kt
>          }
@prayutsu can we use safe calls ` .?` instead of null assertions here and similarly at other instances of `!!` use

2020-09-29 18:59 UTC, prayutsu commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.kt
>          }
Sure, I'll fix this

2020-10-01 16:29 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/EncounterEntity.kt
> +    @Expose
If it wasn't present in previous files, then remove it as those aren't associated with retrofit calls directly

2020-10-01 17:42 UTC, rishabh-997 requested changes
Address the previous changes by Saurabh and me and the rest looks fine. The app ran smoothly on my device... Also, squash commits into one...

2020-10-02 06:27 UTC, prayutsu commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.kt
> +            patient.causeOfDeath = Resource(ApplicationConstants.EMPTY_STRING, patientEntity.causeOfDeath!!, ArrayList(), 0)
```
Smart cast to 'String' is impossible, because 'patientEntity.causeOfDeath' is a mutable property that could have been changed by this time
Add non-null)!!) asserted call
```
Android Studio is complaining with this error

2020-10-02 06:28 UTC, prayutsu commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.kt
>          }
I am able to fix it here only

2020-10-02 07:05 UTC, prayutsu commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.kt
> +            visit.location = visitEntity.visitPlace?.let { LocationEntity(it) }!!
@rishabh-997 Here, we have first used safe call, but it complains if I remove ```!!```

2020-10-02 07:56 UTC, prayutsu commented
@rishabh-997 Once all the changes are approved, I'll finally squash commits.

2020-10-02 07:56 UTC, prayutsu commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/EncounterEntity.kt
> +    @Expose
Done

2020-10-07 10:06 UTC, prayutsu commented
@rishabh-997 Any updates?

2020-10-16 20:23 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.kt
> +import org.openmrs.mobile.models.*
remove star imports... They are not preferred in the latest code conventions...

2020-10-16 20:25 UTC, rishabh-997 requested changes
Just this change and looks good... Also, squash your commits...

2020-12-08 10:31 UTC, rishabh-997 commented
Closing due to inactivity. Ping me if you want to work again on it.

2020-12-08 10:31 UTC, closed without merging