AC-792 Fixing Back Button Intent for Contact Us Activity
openmrs/openmrs-contrib-android-client pull request #817
Opened 2020-10-02 02:21 UTC by Bisht13

## Description of what I changed

Added intent to the back button of the action bar in Contact Us activity.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-792

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2020-10-02 21:25 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/community/contact/ContactUsActivity.kt
> +            val backButtonIntent = Intent(this, LoginActivity::class.java)
This seems to be a work around... You need to find the stack trace to get to the reason behind this behaviour.... What you did have following mistakes...
1. no matter at which activity the user is, pressing back icon will always bring him to login screen
2. You have just added intent on menu button, what if the user clicks back button from bottom? your work around will fail...

2020-10-02 21:26 UTC, rishabh-997 requested changes
Try to find the reason behind this... why is previous activity finished without destroying it

2020-10-03 23:48 UTC, Bisht13 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/community/contact/ContactUsActivity.kt
> +            val backButtonIntent = Intent(this, LoginActivity::class.java)
I tried finding why the saved instance of login activity is not being called. The activity is there in the stack when the contact activity is created but is popped from the stack when the back button is clicked. I was unable to recreate your first issue. The back button of other action bars don't call back to the login page. The second issue called be fixed by using the same work around in onBackPressed function in contact class.

2020-10-04 07:26 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/community/contact/ContactUsActivity.kt
> +            val backButtonIntent = Intent(this, LoginActivity::class.java)
> doesn't call back to the login page

That is because you are logged in and redirected to the dashboard. Consider an instance when you are on the visits page and go to contacts from there. Pressing back will take you to the dashboard rather than the visits page. Try to correct it the right way instead of using workarounds. :100:

2020-10-16 21:43 UTC, rishabh-997 commented
Any updates on this?

2020-10-18 10:46 UTC, Bisht13 commented
I'm having my college counselling this month, so I might not be able to work on it for some time.

2020-10-18 16:59 UTC, rishabh-997 commented
> I'm having my college counselling this month

That's great, fill your choices carefully, and welcome to college life :partying_face:

2020-12-08 10:34 UTC, rishabh-997 commented
Did you happen to find some fix for this?

2020-12-17 19:19 UTC, rishabh-997 commented
Closing due to inactivity. Also, the issue is fixed at #822

2020-12-17 19:20 UTC, closed without merging