AC-847 Nullable view required in onItemSelected LoginValidatorWatcher
openmrs/openmrs-contrib-android-client pull request #818
Opened 2020-10-19 10:17 UTC by pranoppal

## Description of what I changed

made argument view nullable in onItemSelected listener
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-847

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2020-10-19 15:49 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.kt
> +import android.util.Log
remove unused imports

2020-10-19 15:49 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
> +		list.add(Html.fromHtml(getString(R.string.login_location_select) + getString(R.string.req_star)).toString());
correct the indentation

2020-10-19 15:50 UTC, rishabh-997 requested changes
Check the codestyle of Android studio and align it with the OpenMRS codestyle for future PR's

2020-10-20 04:29 UTC, pranoppal commented on openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.kt
> +import android.util.Log
sure

2020-10-20 04:31 UTC, pranoppal commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
> +		list.add(Html.fromHtml(getString(R.string.login_location_select) + getString(R.string.req_star)).toString());
okay, I'll import the codestyle of OPENMRS

2020-10-20 05:44 UTC, pranoppal commented
@rishabh-997 can you check now?

2020-10-21 11:46 UTC, pranoppal commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
> +		list.add(Html.fromHtml(getString(R.string.login_location_select) + getString(R.string.req_star)).toString());
hello, the indentation is correct in IDE but after pushing the changes its coming like this, will look in stackoverflow pages for solution

2020-10-21 17:27 UTC, rishabh-997 commented on .idea/eclipseCodeFormatter.xml
> +        <option name="pathToConfigFileJava" value="$PROJECT_DIR$/../codeformatter.xml" />
This change is not necessary... Undo it

2020-10-21 17:28 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.kt
> +import android.widget.*
Don't use start imports. Not a good practice in open source

2020-10-21 17:29 UTC, rishabh-997 requested changes
address these changes. If the indentation is fine in IDE, then leave it

2020-10-22 04:46 UTC, pranoppal commented on openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.kt
> +import android.widget.*
okay thanks, I'll keep this in mind

2020-10-22 04:54 UTC, pranoppal commented
@rishabh-997 can you check now? 
Also I have one doubt why codecov/patch diff hit is set to target 13.64%? 
Thanks

2020-10-25 16:19 UTC, rishabh-997 approved these changes
Just squash those commits and I'll merge. Good Work...

2020-10-25 16:24 UTC, rishabh-997 commented
> why codecov/patch diff hit is set to target 13.64%?

That is something that dev4 or dev5 have set to keep a check on the unit tests as those are very important way to check the credibility of the code.

2020-10-26 05:10 UTC, pranoppal commented
> > why codecov/patch diff hit is set to target 13.64%?
> 
> That is something that dev4 or dev5 have set to keep a check on the unit tests as those are very important way to check the credibility of the code.

okay, don't know much about unit testing, but will learn along the way. Thanks

2020-10-26 05:29 UTC, pranoppal commented
> Just squash those commits and I'll merge. Good Work...

hey, check now,
Thanks

2020-10-26 06:37 UTC, merged