AC-657 added About section
openmrs/openmrs-contrib-android-client pull request #827
Opened 2021-01-12 04:21 UTC by MasterBlaster99

### Description of what i have changed 
i have added an about section for OpenMRS user can access it through the menu 
![WhatsApp Image 2021-01-11 at 11 46 15 PM](https://user-images.githubusercontent.com/71667923/104269163-9f1c9480-54bb-11eb-8f83-edf7a1f174c2.jpeg)
![WhatsApp Image 2021-01-12 at 9 48 30 AM](https://user-images.githubusercontent.com/71667923/104269182-a8a5fc80-54bb-11eb-9bdf-cf0deef99ca9.jpeg)

2021-01-12 04:24 UTC, MasterBlaster99 commented
Issue is assigned to me

2021-01-13 10:15 UTC, rishabh-997 commented on openmrs-client/src/main/AndroidManifest.xml
> +            android:label="about"
Add this label in string resources and use it directly here.

2021-01-13 10:15 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
> +                Intent intent =new Intent(getApplicationContext(),AboutActivity.class);
Indent in properly.

2021-01-13 10:16 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.java
> +package org.openmrs.mobile.activities;
Add license code here

2021-01-13 10:16 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.java
> +public class AboutActivity extends AppCompatActivity {
Extend it to ACBaseActivity instead.

2021-01-13 10:17 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.java
> +        TextView tv = findViewById(R.id.moreAbout);
use proper names for variables related to what they do

2021-01-13 10:17 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.java
> +         public void onClick(View v) {
Use lambda function here

2021-01-13 10:17 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.java
> +
Why this space?

2021-01-13 10:18 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.java
> +             intent.setData(Uri.parse("https://openmrs.org/about/"));
Store this in ApplicationConstants

2021-01-13 10:19 UTC, rishabh-997 commented on openmrs-client/src/main/res/menu/basic_menu.xml
> +        android:title="About"
Add this in string resource file

2021-01-13 10:19 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +<?xml version="1.0" encoding="utf-8"?>
add license

2021-01-13 10:19 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +
why this space

2021-01-13 10:19 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:layout_marginTop="60dp"
Align it properly

2021-01-13 10:20 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:text="OpenMRS is a global community of truly dedicated, talented, and generous contributors who build and maintain the OpenMRS platform and other, foundational OpenMRS technical produ
store it in string resouce

2021-01-13 10:21 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:text="OpenMRS is a platform that countries and implementers use to create a customized EMR system in response to actual needs on the ground. "
again

2021-01-13 10:21 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:id="@+id/textView3"
give it proper name

2021-01-13 10:21 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:id="@+id/paragraph1"
give proper name

2021-01-13 10:21 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:id="@+id/moreAbout"
give proper name

2021-01-13 10:22 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:text="more >>"
again in string resouce please

2021-01-13 10:22 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:textStyle="bold|italic"
dont do this, use standard fonts

2021-01-13 10:22 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +
why this space

2021-01-13 10:23 UTC, rishabh-997 requested changes
Please go through codes of other activities to get the idea of conventions. Also, use kotlin instead of java. Do this, then I will give more reviews.

2021-01-13 10:25 UTC, rishabh-997 commented
And don't change the template of the description of this PR, check other PR's and follow the convention instead of erasing everything.

2021-01-13 10:55 UTC, MasterBlaster99 commented
> Please go through codes of other activities to get the idea of conventions. Also, use kotlin instead of java. Do this, then I will give more reviews.

Yes sir , I'll work on all of these

2021-01-14 11:51 UTC, MasterBlaster99 commented
> Please go through codes of other activities to get the idea of conventions. Also, use kotlin instead of java. Do this, then I will give more reviews.
I have made the changes 
should i commit

2021-01-14 11:53 UTC, MasterBlaster99 commented
> Please go through codes of other activities to get the idea of conventions. Also, use kotlin instead of java. Do this, then I will give more reviews.

I have made the changes , also used kotlin 
should i make 1 more commit ?

2021-01-15 04:35 UTC, MasterBlaster99 commented
Sir , I have made the changes 
should i commit the changes

2021-01-15 08:02 UTC, rishabh-997 commented
Yes, I dont think there is any other way to check the new changes :laughing: Also, please correct the description, it is still not matching the template

2021-01-15 15:12 UTC, MasterBlaster99 commented
> Yes, I dont think there is any other way to check the new changes 😆 Also, please correct the description, it is still not matching the template
Yes 😅, I have made the changes @rishabh-997 please review

2021-01-15 15:21 UTC, MasterBlaster99 commented
> Yes, I dont think there is any other way to check the new changes 😆 Also, please correct the description, it is still not matching the template

Yes 😅, I have made the changes @rishabh-997 please review

2021-01-16 03:53 UTC, LuGO0 requested changes

2021-01-16 03:53 UTC, LuGO0 commented on openmrs-client/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
did you intentionally remove the copyright ?

2021-01-16 03:53 UTC, LuGO0 commented on openmrs-client/src/main/res/values/strings.xml
>  </resources>
did you add translations?

2021-01-16 04:43 UTC, MasterBlaster99 commented on openmrs-client/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
oh sorry ! i removed it by mistake, i'll fix it

2021-01-16 04:44 UTC, MasterBlaster99 commented on openmrs-client/src/main/res/values/strings.xml
>  </resources>
No, I'll add

2021-01-17 10:11 UTC, MasterBlaster99 commented on openmrs-client/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
I added the copyright

2021-01-17 10:12 UTC, MasterBlaster99 commented on openmrs-client/src/main/res/values/strings.xml
>  </resources>
@LuGO0 i added translations

2021-01-17 10:13 UTC, MasterBlaster99 commented on openmrs-client/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
I added the copyright 
@LuGO0 please review

2021-01-17 10:13 UTC, MasterBlaster99 commented
I have made the changes 
@rishabh-997 , @LuGO0 please review

2021-01-17 11:14 UTC, LuGO0 commented
build is failing look up to it

2021-01-17 13:18 UTC, MasterBlaster99 commented
> build is failing look up to it

2021-01-17 13:18 UTC, MasterBlaster99 commented
> build is failing look up to it

Sir, But the gradle build is running successfully and aslo the app is working fine after changes

2021-01-17 13:54 UTC, MasterBlaster99 commented
> build is failing look up to it

Yes I am looking

2021-01-18 13:25 UTC, MasterBlaster99 commented
> build is failing look up to it

@LuGO0  now the build is successful

2021-01-19 17:09 UTC, LuGO0 commented
> > build is failing look up to it
> 
> now the build is successful
> @LuGO0 please reviw

@rishabh-997 I think we can should share the figma designs for other screens to @MasterBlaster99 so that the about section is also consistent with other screens.

2021-01-20 11:39 UTC, LuGO0 commented
https://www.figma.com/file/LzEJgldSbhdIuBiFQkePf0/OpenMRS-android-designs?node-id=0%3A1 here it is

2021-01-20 16:55 UTC, MasterBlaster99 commented
> https://www.figma.com/file/LzEJgldSbhdIuBiFQkePf0/OpenMRS-android-designs?node-id=0%3A1 here it is, try and make your design consistent with the figma link.

Yes , i am doing

2021-01-20 17:09 UTC, MasterBlaster99 commented
> https://www.figma.com/file/LzEJgldSbhdIuBiFQkePf0/OpenMRS-android-designs?node-id=0%3A1 here it is, try and make your design consistent with the figma link.

Yes , i am trying

2021-01-20 17:09 UTC, MasterBlaster99 commented
> https://www.figma.com/file/LzEJgldSbhdIuBiFQkePf0/OpenMRS-android-designs?node-id=0%3A1 here it is, try and make your design consistent with the figma link.

Yes , i am doing

2021-01-21 07:54 UTC, rishabh-997 commented
> Yes, I am doing

Post the design on Jira issues for review. Standard font and colors are available in the figma link

2021-01-21 07:56 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.kt
> +package org.openmrs.mobile.activities
Move this activity to ContactUs Package. Try to maintain the architecture.

2021-01-21 07:56 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.kt
> +import kotlinx.android.synthetic.main.activity_about.*
Don't use star imports as this is not a good practice.

2021-01-21 08:00 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.kt
> +        setContentView(R.layout.activity_about)
Use ActivityBinding instead as done in other activities.

2021-01-21 08:01 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.kt
> +        OpenMRSWebsiteTextView.setOnClickListener { intent = Intent(Intent.ACTION_VIEW)
Use toggle case to name variables. and send intent to next line.

2021-01-21 08:02 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/AboutActivity.kt
> +            intent.setData(Uri.parse(ApplicationConstants.ABOUT_OPENMRS_URL))
Combine these in a single line.
val intent = Intent(Intent.ACTION_VIEW, Uri.parse(getString(ApplicationConstants.ABOUT_OPENMRS_URL)))

2021-01-21 08:03 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:id="@+id/OpenMRSWebsiteTextView"
again, use toggle case starting with lowercase

2021-01-21 08:04 UTC, rishabh-997 commented on openmrs-client/src/main/res/menu/basic_menu.xml
> +    <item
LogOut option is always at the bottom

2021-01-21 08:05 UTC, rishabh-997 commented on openmrs-client/src/main/res/values-hi/strings.xml
> +    <string name="action_about">के बारे में</string>
How is this a translation for "about"? Use somewhat more meaningful.

2021-01-21 08:05 UTC, rishabh-997 requested changes
Still a lot of changes required, do this meanwhile

2021-01-21 15:33 UTC, MasterBlaster99 commented
> > Yes, I am doing
> 
> Post the design on Jira issues for review. Standard font and colors are available in the figma link

ok

2021-01-22 05:46 UTC, MasterBlaster99 commented
> > Yes, I am doing
> 
> Post the design on Jira issues for review. Standard font and colors are available in the figma link

i have posted the design on jira issues [check it here](https://issues.openmrs.org/issues/?jql=project%20%3D%20AC%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22about%20section%22%20ORDER%20BY%20status%20DESC%2C%20cf%5B10020%5D%20ASC%2C%20priority%20DESC%2C%20updated%20DESC)

2021-01-22 07:23 UTC, MasterBlaster99 commented
I have made the requested changes 
please review the design so i can commit the changes

2021-01-27 10:43 UTC, MasterBlaster99 commented
I have made the changes @rishabh-997 , @LuGO0

2021-01-27 13:46 UTC, MasterBlaster99 commented
@rishabh-997 , @LuGO0  i have made the changes

2021-01-30 13:36 UTC, MasterBlaster99 commented
@rishabh-997 , @LuGO0  please review !!

2021-01-30 21:21 UTC, rishabh-997 commented
> @rishabh-997 , @LuGO0 please review !!

Can you add a combined screenshot in
1. Normal
2. Dark mode
3. Hindi mode

2021-01-31 08:11 UTC, MasterBlaster99 commented
> > @rishabh-997 , @LuGO0 please review !!
> 
> Can you add a combined screenshot in
> 
> 1. Normal
> 2. Dark mode
> 3. Hindi mode

### 1.Normal
![WhatsApp Image 2021-01-31 at 1 33 30 PM (1)](https://user-images.githubusercontent.com/71667923/106378254-49a41b00-63c9-11eb-93f6-7c2d81dfb18b.jpeg)

### 2. Hindi mode 
![WhatsApp Image 2021-01-31 at 1 33 30 PM](https://user-images.githubusercontent.com/71667923/106378334-d5b64280-63c9-11eb-8803-2f986b1ff065.jpeg)

2021-01-31 08:12 UTC, MasterBlaster99 commented
Normal mode and Dark mode are exactly same, as in all other activities

2021-01-31 18:52 UTC, MasterBlaster99 commented
> > @rishabh-997 , @LuGO0 please review !!
> 
> Can you add a combined screenshot in
> 
> 1. Normal
> 2. Dark mode
> 3. Hindi mode


### 1. Normal 
![WhatsApp Image 2021-01-31 at 1 33 30 PM (1)](https://user-images.githubusercontent.com/71667923/106394458-b8fa2900-6422-11eb-9a81-8121b29b2cd0.jpeg)

### 2. Dark mode 
![darkOpenMRS](https://user-images.githubusercontent.com/71667923/106394535-0f676780-6423-11eb-8b25-bebb23532e38.jpeg)


### 3. Hindi mode 
![WhatsApp Image 2021-01-31 at 1 33 30 PM](https://user-images.githubusercontent.com/71667923/106394494-e941c780-6422-11eb-9cff-0fda6055f32a.jpeg)

2021-02-02 08:34 UTC, MasterBlaster99 commented
@LuGO0 , @rishabh-997  please review !!

2021-02-02 13:06 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/community/contact/AboutActivity.kt
> +        binding.mOREaBOUToPENMRSbUTTON.setOnClickListener {
Use standard naming conventions as in other activities. This looks too weird :laughing:

2021-02-02 13:08 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:id="@+id/aBOUToPENMRStEXTvIEW1"
use a proper naming convention.

2021-02-02 13:08 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:id="@+id/aBOUToPENMRStEXTvIEW2"
use a proper naming convention.

2021-02-02 13:09 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:textSize="22sp"
make it around 18-20sp

2021-02-02 13:09 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:id="@+id/mOREaBOUToPENMRSbUTTON"
use a proper naming convention.

2021-02-02 13:12 UTC, rishabh-997 requested changes
Also, take a look at the stack hierarchy. moving from settings->about->setting->about->so...on creates a piling stack.

2021-02-02 15:40 UTC, MasterBlaster99 commented
> Also, take a look at the stack hierarchy. moving from settings->about->setting->about->so...on creates a piling stack.

should i make only "settings" visible in the menu of about activity ?

2021-02-02 15:42 UTC, MasterBlaster99 commented
> Also, take a look at the stack hierarchy. moving from settings->about->setting->about->so...on creates a piling stack.

I did not understood what i exactly have to do here 🤔

2021-02-02 16:27 UTC, rishabh-997 commented
> I did not understand what I exactly have to do here

https://user-images.githubusercontent.com/45125121/106630090-8591d880-65a1-11eb-81bc-c67f46e07529.mp4

2021-02-02 18:22 UTC, MasterBlaster99 commented
> > I did not understand what I exactly have to do here
> 
>  WhatsApp.Video.2021-02-02.at.9.54.07.PM.mp4

Oh! Got it , thank you

2021-02-03 19:30 UTC, MasterBlaster99 commented
@rishabh-997 Done !

2021-02-05 11:23 UTC, MasterBlaster99 commented
@rishabh-997 , @LuGO0  please review !!

2021-02-07 11:54 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:layout_height="42dp"
use wrap content and also use gravity to make the text at the centre of the button.

2021-02-07 11:54 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:textSize="20sp"
This too.

2021-02-07 11:54 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_about.xml
> +        android:textSize="20sp"
This still looks too big for a descriptive text. make this 18sp

2021-02-07 11:55 UTC, rishabh-997 requested changes
LGTM. just these 2 changes and looks fine.

2021-02-07 15:49 UTC, MasterBlaster99 commented
> LGTM. just these 2 changes and looks fine.

@rishabh-997 Made the Changes, Please Review !!

2021-02-07 20:42 UTC, rishabh-997 approved these changes
LGTM!!!

2021-02-07 20:43 UTC, merged