AC-868: Updated Address EditText fields
openmrs/openmrs-contrib-android-client pull request #837
Opened 2021-02-03 06:12 UTC by amtheshubham

AC-868: Address Edittext hint should mention "Address Line" instead of "Address"

## Description of what I changed

In the Register Patient Activity, in the Edittext field of Address there should be a hint like "Address Line 1", "Address Line 2" instead of only "Address".

Before: Address 1, Address 2
Now: Address Line 1, Address Line 2

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-868

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- No new tests required.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### Screenshots
**Old**

![Old](https://user-images.githubusercontent.com/52814595/106705833-b2cb9e80-6614-11eb-9c25-4caee496ef4d.JPG)
**New**

![New](https://user-images.githubusercontent.com/52814595/106705836-b3fccb80-6614-11eb-88cc-93c55e5f6590.JPG)

2021-02-03 11:35 UTC, HerbertYiga commented
thanks @amtheshubham

2021-02-03 11:35 UTC, HerbertYiga approved these changes

2021-02-07 11:57 UTC, rishabh-997 commented on openmrs-client/src/main/res/values/strings.xml
> +    <string name="addr2_hint">Address Line 2</string>
Update this line in Hindi strings.xml too

2021-02-07 11:59 UTC, rishabh-997 requested changes
Also, please don't send -4 PR's for issues like this. Go Through the git-rebase tutorial and see how to correct git history. Multiple Pr's is not a good practice.

2021-02-07 16:18 UTC, amtheshubham commented
@rishabh-997 I know how to rebase and all but as explained I ran into some other problem which couldn't be fixed. However, I will take care. I have updated Hindi strings.xml file.

2021-02-07 20:44 UTC, rishabh-997 approved these changes
LGTM

2021-02-07 20:45 UTC, merged