AC-871: Added Navigation Graph for Dashboard Activity
openmrs/openmrs-contrib-android-client pull request #841
Opened 2021-02-04 14:22 UTC by amtheshubham

## Description of what I changed
This is the first progress towards "Migration to Navigation Component". Added "Dashboard_nav_graph" for transitions of Fragments and Activities from this Activity.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-871

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] No new tests required

- [x] All existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

![navGraphDashboard](https://user-images.githubusercontent.com/52814595/106905514-5eaee000-6722-11eb-9c63-6dc82b4ec159.JPG)

2021-02-04 14:49 UTC, amtheshubham commented
@LuGO0 Please Review. This is the new PR.

2021-02-05 06:10 UTC, LuGO0 commented
can you add a GIF showing the workflow ?

2021-02-05 06:16 UTC, LuGO0 requested changes

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/build.gradle
> +
add this to the versions file

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
remove this resolve the warning its bad to supress lint warnings.

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsFragment.kt
what if the context is null how will the app react in case of a NPE

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyFragment.java
similarly

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
>      }
similarly what in case of NPE

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardContract.kt
>  interface DashboardContract {
remove this comment

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientDashboardAllergyPresenter.java
>      @Override
remove and find a way.

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
>                  .getSerializableExtra(ApplicationConstants.BundleKeys.PROVIDER_ID_BUNDLE));
what in case of NPE

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
>                  .getSerializableExtra(ApplicationConstants.BundleKeys.EXISTING_PROVIDERS_BUNDLE));
what in case of NPE

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsRecyclerViewAdapter.java
>              return true;
similar what in case of NPE

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/res/layout/activity_dashboard.xml
fix indentation

2021-02-05 06:16 UTC, LuGO0 commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +</navigation>
add licence

2021-02-05 06:32 UTC, LuGO0 commented
@amtheshubham add tiket id to commit messages

2021-02-05 06:46 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsFragment.kt
Old version: In the "**context!!**", we are using **!!** operator which means we want a **NPE** to be thrown when context is _null_.
New version: I replaced it with "**requireContext()**", which does the same i.e., It throws **NPE** when context is _null_ so no difference between them.

Moreover, I did not change any of the code except for the Dashboard Activity and Fragment for Navigation Components. I changed other files because Lint was giving a warning but I didn't change anything in those files.

2021-02-05 06:52 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsRecyclerViewAdapter.java
>              return true;
Similarly, No difference between **Objects.requireNonNull(mContext.getActivity())** & **mContext.requireActivity()**. They both throw NPE when there is not _Activity_ associated. I just used the new methods.

2021-02-05 06:53 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyFragment.java
They both mean same thing i.e., "**Throw a NPE when null is encountered**"

2021-02-05 06:54 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
>      }
They both mean same thing i.e., "**Throw a NPE when null is encountered**"

2021-02-05 06:54 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
>                  .getSerializableExtra(ApplicationConstants.BundleKeys.PROVIDER_ID_BUNDLE));
They both mean same thing i.e., "**Throw a NPE when null is encountered**"

2021-02-05 06:54 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
>                  .getSerializableExtra(ApplicationConstants.BundleKeys.EXISTING_PROVIDERS_BUNDLE));
They both mean same thing i.e., "**Throw a NPE when null is encountered**"

2021-02-05 06:59 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
I deliberately added this because Lint was giving an error to change the minSdk version which I think **I am not allowed to do** . Moreover, again I did not change anything here but faced an error in the Lint. Though GRADLE BUILD is successfully compiled.
If you give me permission, I can change the minSdk version otherwise this is the only solution to suppress this error.

2021-02-05 06:59 UTC, amtheshubham commented on openmrs-client/build.gradle
> +
sure

2021-02-05 07:00 UTC, amtheshubham commented on openmrs-client/src/main/res/layout/activity_dashboard.xml
sure

2021-02-05 07:00 UTC, amtheshubham commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +</navigation>
sure

2021-02-05 14:35 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
I dont think there is a need to supress the warning, it can be left like it. cc @rishabh-997

2021-02-05 14:37 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
>      }
okay cool sometimes these things make the app unstable could we introduce null checks? you can resolve all other similar issues.

2021-02-05 14:43 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
>      }
We **shouldn't** perform _null checks_ here @LuGO0 because We want the app to **throw NPE** If there isn't any activity or context associated. That way we can see the **stacktrace** & resolve it and that's the whole point of **!!** operator. However, you guys know better. Here to learn,

2021-02-05 14:46 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
I would've left it as It was but you said "**Travis**" and "**Appveyor**" were throwing errors for _Lint_ warnings.

2021-02-05 15:05 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
I think we had `abortOnError false` setup for lint warings.

2021-02-05 15:07 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
https://github.com/openmrs/openmrs-contrib-android-client/blame/72f095675fdf673819d224314a844f1e08d44673/openmrs-client/build.gradle#L44 @rishabh-997 could you look upto it?

2021-02-12 05:00 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
@amtheshubham could you make one more Issue about lint warnings and get it done before this one ? I think warnings should not abort a build and we should have that flag set to false,
could you just make the Issue for lint warnings and maybe whats the best practice about this flag and handle it accordingly?

2021-02-12 05:08 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
Yeah this sounds good. I will get it done👍

2021-02-13 18:26 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
>      public void setupTheme() {
For now, I have rectified all the _Lint_ errors and refactored some tests so this PR is ready to be merged.

After a lot of research on this, I have decided not to go for "`Setting the abortonerror flag to false`". Since we are migrating to _Navigation Component_, _Lint_ requires that the App is _not_ using deprecated methods and libraries. Though `BUILD` is everytime successful but _Lint_ gives some errors as most of the libraries and methods used in the project are deprecated. It would be better, If the app had latest libraries and _MVVM_ pattern before using _Navigation Component_ but nevertheless I will resolve all _Lint_ Warnings related to _Navigation Component_, whatever It takes. We should think about setting that _flag_ to `false` or _suppressing_ them only in unavoidable circumstances, which I think could arrive in future.

2021-02-13 19:47 UTC, amtheshubham commented
@rishabh-997 After approval of changes, if you want I will squash all commits to one👍

2021-02-14 08:53 UTC, rishabh-997 commented on build.gradle
> +
remove extra spaces.

2021-02-14 08:53 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardActivity.kt
> +
remove extra spaces.

2021-02-14 08:53 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardContract.kt
>  interface DashboardContract {
Yes, please.

2021-02-14 08:54 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardPresenter.kt
> +
remove spaces.

2021-02-14 08:54 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardPresenter.kt
> +
remove these comments.

2021-02-14 08:56 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionFragment.kt
> +    @SuppressLint("UseRequireInsteadOfGet")
Your views on this one @LuGO0 as I wasn't following your conversation in this PR.

2021-02-14 08:58 UTC, rishabh-997 commented on openmrs-client/src/main/res/layout/activity_patient_info.xml
> +    xmlns:tools="http://schemas.android.com/tools"
keep this at the top of other attributes.

2021-02-14 08:59 UTC, rishabh-997 commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +    <activity
keep a blank line between different tags.

2021-02-14 09:01 UTC, rishabh-997 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardAllergyPresenterTest.java
> -
why these changes?

2021-02-14 09:02 UTC, rishabh-997 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardAllergyPresenterTest.java
> -
why these changes?

2021-02-14 09:02 UTC, rishabh-997 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardAllergyPresenterTest.java
> -
why these changes?

2021-02-14 09:03 UTC, rishabh-997 requested changes
I'll run the changes in the studio after this to check if it's working.

2021-02-14 09:07 UTC, amtheshubham commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardAllergyPresenterTest.java
> -
Just removed the extra line spaces. I refactored a test so I thought I might have added these spaces.

2021-02-14 09:18 UTC, rishabh-997 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardAllergyPresenterTest.java
> -
Check other tests, Android Studio creates a space between packages of different category.

2021-02-14 09:31 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionFragment.kt
> +    @SuppressLint("UseRequireInsteadOfGet")
I will remove this line. I already have rectified the Lint error.

2021-02-18 07:59 UTC, amtheshubham commented
The App is working fine. I tested the Register Patient button, for which I added Navigation direction

https://user-images.githubusercontent.com/52814595/108323982-590acd00-71ed-11eb-90bf-c386d25fceb5.mp4

2021-02-18 17:08 UTC, rishabh-997 commented
> The App is working fine. I tested the Register Patient button, for which I added Navigation direction

I am having my mid-sem exams till 23rd so if @LuGO0 approves it, I'll just merge directly :)

2021-02-21 08:35 UTC, LuGO0 commented
> > The App is working fine. I tested the Register Patient button, for which I added Navigation direction
> 
> I am having my mid-sem exams till 23rd so if @LuGO0 approves it, I'll just merge directly :)

works fine for me in normal usage did not test for lower APIs @amtheshubham can you do the same?

2021-02-23 12:32 UTC, amtheshubham commented
> > > The App is working fine. I tested the Register Patient button, for which I added Navigation direction
> > 
> > 
> > I am having my mid-sem exams till 23rd so if @LuGO0 approves it, I'll just merge directly :)
> 
> works fine for me in normal usage did not test for lower APIs @amtheshubham can you do the same?

@LuGO0 Please tell the specific API versions I should test the App on?

2021-02-24 08:32 UTC, rishabh-997 commented
> @LuGO0 Please tell the specific API versions I should test the App on?

try for API Level 20

2021-02-24 16:20 UTC, amtheshubham commented
> > @LuGO0 Please tell the specific API versions I should test the App on?
> 
> try for API Level 20

There is no **API Level 20** however I have tested the app on **API Level 21**. Here is the video (_I have shown the Android version of API 21 i.e., 5.1 )_

https://user-images.githubusercontent.com/52814595/109030013-70642180-76e9-11eb-9d98-77de494c2868.mp4

2021-02-24 17:03 UTC, rishabh-997 approved these changes
Nice... Thanks for the contribution

2021-02-24 17:03 UTC, merged

2021-02-26 20:48 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
@rishabh-997 is this fine to do in MVP pattern which we are following at present it should be following the fragment contract right @amtheshubham ?? this defeats the whole purpose of having contracts IMO.

2021-02-26 20:54 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
@LuGO0 I know but I did it intentionally as there is no other task in this Fragment other than binding drawables that's why I abstracted it out and also my intention was to convert this into MVVM which I will do in future. I thought It's understandable as It was not pointed out by you guys when I made this change.

2021-02-26 20:59 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
Yes lets wait for rishabh to have a say on this I think it should be kept that way untill it completely migrates to MVVM because that this way we are in middle not in MVP neither in MVVM