AC-706 disabled user screen interaction while patient is being regist…
openmrs/openmrs-contrib-android-client pull request #844
Opened 2021-02-09 05:59 UTC by MasterBlaster99

## Description of what I changed
I have removed the user-screen interaction while the patient is being registered 

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-706

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

 

https://user-images.githubusercontent.com/71667923/107322169-f36e6080-6ac9-11eb-91f2-a7e1f8631c44.mp4

2021-02-09 06:02 UTC, MasterBlaster99 commented
@rishabh-997, this only works when the progress bar is visible
it works after checking the Edit Texts

2021-02-09 08:34 UTC, MasterBlaster99 commented
> @rishabh-997,now this works fine
> this only works when the progress bar is visible
> it works after checking all the Edit Texts

2021-02-13 15:32 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
> +        getActivity().getWindow().setFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE,WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE);
Can you also add a 70-80% translucent view like this which is visible during loading?
https://images.app.goo.gl/e1Rx9tGZXUuhKR6i8

2021-02-13 15:32 UTC, rishabh-997 requested changes
Add this too!

2021-02-17 07:04 UTC, MasterBlaster99 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
> +        getActivity().getWindow().setFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE,WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE);
added

2021-02-17 07:05 UTC, MasterBlaster99 commented
> Add this too!

Added the 70% translucent View @rishabh-997 please Review !!

2021-02-17 07:12 UTC, MasterBlaster99 commented
> > Add this too!
> 
> Added the 70% translucent View @rishabh-997 please Review !!

![WhatsApp Image 2021-02-17 at 12 38 27 PM](https://user-images.githubusercontent.com/71667923/108168552-812afb00-711d-11eb-8a9a-7c3ba04be1ed.jpeg)

2021-02-23 17:51 UTC, MasterBlaster99 commented
@rishabh-997  please review !!

2021-02-24 17:19 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
> +        pd.show();
how are you countering repeated usage??? The function `setProgressBarVisibility` does both switching and hiding ProgressBar, but how is the state changed for view???

2021-02-24 17:20 UTC, rishabh-997 requested changes
Address this query.

2021-02-25 13:47 UTC, MasterBlaster99 commented
> Address this query.

😕 i am not getting this , what should i do exactly ?

2021-02-25 18:52 UTC, rishabh-997 commented
> > Address this query.
> 
> 😕 i am not getting this , what should i do exactly ?

suppose you cluck submit and progress bar starts rotating along with translucent background... now suppose there is some error which makes the setProgressBarVisibility function false and progress bar stops, in that case how will the translucent background and touch interaction stop???

2021-03-01 18:17 UTC, MasterBlaster99 commented
> > > Address this query.
> > 
> > 
> > 😕 i am not getting this , what should i do exactly ?
> 
> suppose you cluck submit and progress bar starts rotating along with translucent background... now suppose there is some error which makes the setProgressBarVisibility function false and progress bar stops, in that case how will the translucent background and touch interaction stop???

i have made the changes ! when an error occurs and setProgressBarVisibility is set to false, now the user will get back the screen interaction. But i have removed the translucent background , i am not able remove it if the setProgressBar is false

2021-03-13 18:53 UTC, rishabh-997 commented
> removed the translucent background

Try to find a solution for this, there is nothing that can't be done, all it takes is innovative thought and stackOverflow

2021-03-20 20:13 UTC, MasterBlaster99 commented
Done!!
@rishabh-997 please review

> > removed the translucent background
> 
> Try to find a solution for this, there is nothing that can't be done, all it takes is innovative thought and stackOverflow

Done!!
@rishabh-997 please review

2021-04-02 08:13 UTC, MasterBlaster99 commented
@rishabh-997  please review!

2021-05-05 04:24 UTC, LuGO0 approved these changes
LGTM @rishabh-997 we can merge this.

2021-06-10 18:00 UTC, MasterBlaster99 commented
> LGTM @rishabh-997 we can merge this.

@rishabh-997  yes 🥺

2021-08-19 15:35 UTC, merged