AC-873 Refactored the repository section
openmrs/openmrs-contrib-android-client pull request #845
Opened 2021-02-11 19:48 UTC by LuGO0

## Description of what I changed
Refactored the Unit tests as well as the code to encorporate an abstract hierarchy.
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-873

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-02-12 04:57 UTC, LuGO0 commented
@rishabh-997 please review !!

2021-02-12 05:29 UTC, LuGO0 commented
@rishabh-997 on a side-note is codeCoverage tool working?

2021-02-12 06:59 UTC, HerbertYiga commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderDashboardPresenterTest.java
> +
you can remove this added line too

2021-02-12 07:15 UTC, LuGO0 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderDashboardPresenterTest.java
> +
Sure @HerbertYiga I will remove this line once my PR gets reviewed 👍

2021-02-13 15:37 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/BaseRepository.java
> +    // used in Unit tests
Remove this comment,

2021-02-13 15:38 UTC, rishabh-997 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderDashboardPresenterTest.java
> +        this.providerRepository = new ProviderRepository(openMRS,restApi);
add a space after the comma.

2021-02-13 15:39 UTC, rishabh-997 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderManagerDashboardPresenterTest.java
> +        this.providerRepository = new ProviderRepository(openMRS,restApi);
add space after the comma.

2021-02-13 15:40 UTC, rishabh-997 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormAdmissionPresenterTest.java
> +        this.providerRepository = new ProviderRepository(openMRS,restApi);
add a space.

2021-02-13 15:40 UTC, rishabh-997 requested changes
Yo.

2021-02-13 15:44 UTC, LuGO0 commented on openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormAdmissionPresenterTest.java
> +        this.providerRepository = new ProviderRepository(openMRS,restApi);
Oops I forgot reformatting doing it 👍

2021-02-14 08:35 UTC, rishabh-997 approved these changes

2021-02-14 08:36 UTC, merged