AC-870: Use of Viewbinding instead of findViewbyId calls in Dashboard fragment
openmrs/openmrs-contrib-android-client pull request #846
Opened 2021-02-12 07:59 UTC by amtheshubham

## Description of what I changed
I have replaced `findViewById` calls by _**ViewBinding**_ in Dashboard fragment to ensure compile time safety.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-870

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**

- [ ] No new tests required

- [x] All existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-02-13 07:30 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
>      private var mFindPatientButton: ImageView? = null
should It be private access Modifier?

2021-02-13 07:30 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
> +        val root = binding!!.root
could you reformat the file and remove extra spaces added.

2021-02-13 15:36 UTC, rishabh-997 requested changes
Use view binding inside `showOverlayTutorial` function too.

2021-02-13 16:49 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
> +        val root = binding!!.root
Done!

2021-02-13 16:49 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
>      private var mFindPatientButton: ImageView? = null
Done!

2021-02-14 08:31 UTC, rishabh-997 approved these changes

2021-02-14 08:31 UTC, merged