AC-874 Restructured provider and patient repositories
openmrs/openmrs-contrib-android-client pull request #847
Opened 2021-02-15 18:55 UTC by LuGO0

1. refactored Tests related to the changes and used the parents members instead of instanciating a new variable.

## Description of what I changed

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-874

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-02-16 05:04 UTC, LuGO0 commented
@rishabh-997 please review !!

2021-02-24 08:34 UTC, rishabh-997 requested changes
rest looks fine to me

2021-02-24 08:34 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.kt
> +import org.openmrs.mobile.models.*
star import 😆

2021-02-24 12:09 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.kt
> +import org.openmrs.mobile.models.*
Oops need to fix my formatting :(

2021-02-25 09:50 UTC, rishabh-997 approved these changes

2021-02-25 09:51 UTC, merged

2021-02-26 09:31 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
> +        Call<IdGenPatientIdentifiers> call = restApi.getPatientIdentifiers(openMrs.getUsername(), openMrs.getPassword());
**Before this merge:**

![notnull](https://user-images.githubusercontent.com/52814595/109282351-6ce4ad80-7843-11eb-94f3-28eaa699014e.JPG)

2021-02-26 09:32 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
> +        Call<IdGenPatientIdentifiers> call = restApi.getPatientIdentifiers(openMrs.getUsername(), openMrs.getPassword());
@amtheshubham please make a new Issue for this lets Investigate it, not sure why the app is crashing 🤔

2021-02-26 09:39 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
> +        Call<IdGenPatientIdentifiers> call = restApi.getPatientIdentifiers(openMrs.getUsername(), openMrs.getPassword());
@LuGO0 I am working on **two** more issues. As this is your PR(_merged just yesterday_) and you know better about your work done on this, I think this issue should be opened by you. I am trying to understand this though🙂

2021-02-26 09:41 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
> +        Call<IdGenPatientIdentifiers> call = restApi.getPatientIdentifiers(openMrs.getUsername(), openMrs.getPassword());
Sure I will Open a new Issue thought you wanted to take this up since you reported it, I will take this up now 👍🏼

2021-02-26 09:46 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
> +        Call<IdGenPatientIdentifiers> call = restApi.getPatientIdentifiers(openMrs.getUsername(), openMrs.getPassword());
I would've been more than happy to take this but I am not having a good idea about what this PR is about. Stumbled into this issue while I was testing my changes then I saw the issue is in the master branch.

2021-02-26 09:48 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
> +        Call<IdGenPatientIdentifiers> call = restApi.getPatientIdentifiers(openMrs.getUsername(), openMrs.getPassword());
@rishabh-997 I request you to revert this merge from **master** as _contributors_ can face problems with this merge (As I  just encountered one)

2021-02-26 10:13 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
> +        Call<IdGenPatientIdentifiers> call = restApi.getPatientIdentifiers(openMrs.getUsername(), openMrs.getPassword());
I cannot revert it directly, as it might end up creating errors with other merged PR's as well. It would be better to investigate this issue.