AC-879 Migrated Form List Package from Java to Kotlin
openmrs/openmrs-contrib-android-client pull request #848
Opened 2021-02-17 20:16 UTC by shivamsawlani02

## Description of what I changed
Migrated four classes of FormList Package which were originally in Java to Kotlin.

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-879

## Checklist: I completed these to help reviewers :)
- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-02-17 20:35 UTC, shivamsawlani02 commented
After migrating to kotlin the Form List activity is working fine as can be seen in the video below.


https://user-images.githubusercontent.com/56927750/108264433-89228380-718d-11eb-85da-38b54e8c8958.mp4

2021-02-18 13:07 UTC, HerbertYiga commented
cc @LuGO0

2021-02-19 15:27 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListFragment.kt
> +            val typeface = Typeface.createFromAsset(activity!!.assets, ApplicationConstants.TypeFacePathConstants.ROBOTO_MEDIUM)
use **requireactivity()** instead of **activity!!** as **activity!!** throws NPE when fragment is not found while **requireactivity()** throws a more specific exception.

2021-02-19 15:28 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListFragment.kt
> +        formList?.adapter = ArrayAdapter(context!!,
similarly use **requirecontext()** because **context!!** throws NPE

2021-02-19 15:29 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListActivity.kt
> +import org.openmrs.mobile.activities.formadmission.FormAdmissionFragment
I think this is an unused import

2021-02-19 15:31 UTC, amtheshubham commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListFragment.kt
> +            val `is` = activity!!.assets.open("forms/$filename")
similarly

2021-02-22 08:53 UTC, shivamsawlani02 commented
Made the changes.

2021-02-22 08:54 UTC, shivamsawlani02 commented
@rishabh-997 @LuGO0 please review these changes.

2021-02-24 17:06 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListActivity.kt
> +        // Create fragment
Remove this comment.

2021-02-24 17:07 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListActivity.kt
> +        var formListFragment = supportFragmentManager.findFragmentById(R.id.formListContentFrame) as FormListFragment?
Since we are migrating to kotlin, you can as well use view binding instead.

2021-02-24 17:07 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListActivity.kt
> +        // Create the presenter
Remove this comment

2021-02-24 17:12 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListFragment.kt
> +        root = inflater.inflate(R.layout.fragment_form_list, container, false)
use view binding here

2021-02-24 17:13 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListPresenter.kt
> +import java.util.*
remove star imports.

2021-02-24 17:13 UTC, rishabh-997 requested changes
Done.

2021-02-24 18:32 UTC, shivamsawlani02 commented
Made the changes. Please review.

2021-02-25 09:48 UTC, rishabh-997 approved these changes

2021-02-25 09:49 UTC, merged