AC-875: Added Navgraph directions for dashboard buttons
openmrs/openmrs-contrib-android-client pull request #852
Opened 2021-02-26 12:53 UTC by amtheshubham

Navigation Component is now available in the app, so used 'compile-time-safe' activity transactions methods for the Dashboard

## Description of what I changed

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-875

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**

- [ ] No new tests required

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-02-26 12:56 UTC, amtheshubham commented
The App is working absolutely fine!


https://user-images.githubusercontent.com/52814595/109302938-0326cc80-7860-11eb-9d47-c5affbaeb040.mp4

2021-03-01 06:08 UTC, amtheshubham commented
@LuGO0 Review please

2021-03-13 19:07 UTC, amtheshubham commented
@rishabh-997 Have a look

2021-03-13 19:22 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
> +        val directionToFindPatent=DashboardFragmentDirections.actionDashboardFragmentToSyncedPatientsActivity()
Follow code conventions... add spacing properly. `abc = xyz`

2021-03-13 19:22 UTC, rishabh-997 requested changes
See to it

2021-03-13 19:32 UTC, amtheshubham commented
> See to it

Done!

2021-03-17 07:20 UTC, merged

2021-03-17 19:13 UTC, shivamsawlani02 commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +        android:name="org.openmrs.mobile.activities.providerdashboard.ProviderDashboardActivity"
@amtheshubham, I think it should be ProviderManagerDashboardActivity instead of ProviderDashboardActivity. Can you please verify?

2021-03-17 19:19 UTC, amtheshubham commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +        android:name="org.openmrs.mobile.activities.providerdashboard.ProviderDashboardActivity"
yes @shivamsawlani02 right. Thanks for noticing. You want to take this issue up or should I fix it?

2021-03-17 19:23 UTC, shivamsawlani02 commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +        android:name="org.openmrs.mobile.activities.providerdashboard.ProviderDashboardActivity"
Anything would be fine. I will raise a new issue and send a pull request.

2021-03-17 19:25 UTC, amtheshubham commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +        android:name="org.openmrs.mobile.activities.providerdashboard.ProviderDashboardActivity"
Ping me If you face any problem

2021-03-17 19:27 UTC, amtheshubham commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +        android:name="org.openmrs.mobile.activities.providerdashboard.ProviderDashboardActivity"
@shivamsawlani02 I guess this will also fix the issue you addressed in AC-910? Try reproducing the bug which you reported after you are done with the fix.