AC-888 Migrated Login Package from Java to Kotlin
openmrs/openmrs-contrib-android-client pull request #858
Opened 2021-03-13 10:56 UTC by shivamsawlani02

## Description of what I changed
Migrated Login Package which consisted of five files(Activity, Contract, Presenter, Fragment, and Location Adapter) from java to kotlin.

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-888

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-03-13 17:19 UTC, LuGO0 commented
@shivamsawlani02 did you check the travis?

2021-03-13 17:46 UTC, shivamsawlani02 commented
@LuGO0 yes I checked but could not configure why the travis build is failing.

2021-03-13 18:36 UTC, shivamsawlani02 commented
@LuGO0 the Travis CI build passed successfully now.

2021-03-13 22:07 UTC, sahuadarsh0 commented
👍🏼

2021-03-17 07:24 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LocationArrayAdapter.kt
> +        val v: View
use more informative naming convention

2021-03-17 07:24 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LocationArrayAdapter.kt
> +            val tv = TextView(context)
same here

2021-03-17 07:29 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
> +                binding!!.textInputLayoutPassword.hint = Html.fromHtml(getString(R.string.login_password_hint) + getString(R.string.req_star))
use with(binding) {
/////
}

2021-03-17 07:29 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
> +        binding!!.forgotPass.setOnClickListener { view: View? -> startActivity(Intent(context, ContactUsActivity::class.java)) }
use with(binding) {
/////
}

2021-03-17 07:29 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
> +        binding!!.textInputLayoutUsername.hint = Html.fromHtml(getString(R.string.login_username_hint) + getString(R.string.req_star))
use with(binding) {
/////
}

2021-03-17 07:29 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
> +        binding!!.loginFormView.visibility = View.VISIBLE
use with(binding) {
/////
}

2021-03-17 07:29 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
> +        binding!!.loginFormView.visibility = View.GONE
use with(binding) {
/////
}

2021-03-17 07:29 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
> +        binding!!.loginLoading.visibility = View.GONE
similarly everwhere

2021-03-17 07:30 UTC, rishabh-997 requested changes
.

2021-03-17 11:16 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
> +                binding!!.textInputLayoutPassword.hint = Html.fromHtml(getString(R.string.login_password_hint) + getString(R.string.req_star))
Wow! Had never used 'with' function before. Thanks for the info.

2021-03-17 11:17 UTC, shivamsawlani02 commented
@rishabh-997 made the changes. Please review.

2021-03-19 10:17 UTC, sahuadarsh0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
> +        binding!!.loginFormView.visibility = View.VISIBLE
also binding.apply { 
////
}
can be used

2021-08-19 15:38 UTC, LuGO0 commented
Closing this for now. please open the PR again after fixing the merge conflicts. thanks

2021-08-19 15:38 UTC, closed without merging