AC-929 Changed ProviderDashboardActivity to ProviderManagerDashboardActivity in Nav Graph
openmrs/openmrs-contrib-android-client pull request #871
Opened 2021-03-17 19:43 UTC by shivamsawlani02

## Description of what I changed
Changed ProviderDashboardActivity to ProviderManagerDashboardActivity in Nav Graph.
Reference - Comments in this PR  https://github.com/openmrs/openmrs-contrib-android-client/pull/852

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-929

## Checklist: I completed these to help reviewers :)
- [x] My pull request only contains **ONE single commit**

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-03-17 19:50 UTC, amtheshubham commented
@shivamsawlani02 Also refactor the `directionToProviderManager` variable in `DashboardFragment.kt`

2021-03-17 19:55 UTC, amtheshubham reviewed
@shivamsawlani02 First change the following lines in the dashboard_nav_graph.xml
```
<action
            android:id="@+id/action_dashboardFragment_to_providerDashboardActivity"
            app:destination="@id/providerDashboardActivity" />
```
Then after this, rebuild the project. Then at last, change the variable of direction in the `DashboardFragment.kt`

Without all this, issue won't be solved

2021-03-17 19:59 UTC, shivamsawlani02 commented
> @shivamsawlani02 First change the following lines in the dashboard_nav_graph.xml
> 
> ```
> <action
>             android:id="@+id/action_dashboardFragment_to_providerDashboardActivity"
>             app:destination="@id/providerDashboardActivity" />
> ```
> 
> Then after this, rebuild the project. Then at last, change the variable of direction in the `DashboardFragment.kt`
> 
> Without all this, issue won't be solved

The issue is solved without this. But you are right. The names should be changed.

2021-03-17 20:02 UTC, amtheshubham commented
> > @shivamsawlani02 First change the following lines in the dashboard_nav_graph.xml
> > ```
> > <action
> >             android:id="@+id/action_dashboardFragment_to_providerDashboardActivity"
> >             app:destination="@id/providerDashboardActivity" />
> > ```
> > 
> > 
> > Then after this, rebuild the project. Then at last, change the variable of direction in the `DashboardFragment.kt`
> > Without all this, issue won't be solved
> 
> The issue is solved without this. But you are right. The names should be changed.

It will create unnecessary confusion and hence will still remain an issue

2021-03-17 20:03 UTC, shivamsawlani02 commented
> > > @shivamsawlani02 First change the following lines in the dashboard_nav_graph.xml
> > > ```
> > > <action
> > >             android:id="@+id/action_dashboardFragment_to_providerDashboardActivity"
> > >             app:destination="@id/providerDashboardActivity" />
> > > ```
> > > 
> > > 
> > > Then after this, rebuild the project. Then at last, change the variable of direction in the `DashboardFragment.kt`
> > > Without all this, issue won't be solved
> > 
> > 
> > The issue is solved without this. But you are right. The names should be changed.
> 
> It will create unnecessary confusion and hence will still remain an issue

Yes I will change the names and then push.

2021-03-17 20:06 UTC, amtheshubham commented
> > > > @shivamsawlani02 First change the following lines in the dashboard_nav_graph.xml
> > > > ```
> > > > <action
> > > >             android:id="@+id/action_dashboardFragment_to_providerDashboardActivity"
> > > >             app:destination="@id/providerDashboardActivity" />
> > > > ```
> > > > 
> > > > 
> > > > Then after this, rebuild the project. Then at last, change the variable of direction in the `DashboardFragment.kt`
> > > > Without all this, issue won't be solved
> > > 
> > > 
> > > The issue is solved without this. But you are right. The names should be changed.
> > 
> > 
> > It will create unnecessary confusion and hence will still remain an issue
> 
> Yes I will change the names and then push.

You can just rebuild the project, It will automatically be changed

2021-03-17 21:09 UTC, shivamsawlani02 commented
@amtheshubham have a look now.

2021-03-18 09:06 UTC, amtheshubham commented
> @amtheshubham have a look now.

There are failed checks. Please rectify

2021-03-18 12:35 UTC, amtheshubham commented
@shivamsawlani02 Rebase your local master branch with the origin(i.e.,OpenMRS master) so that your local master first receives the latest changes from the project. Then make a branch and commit.

2021-03-18 12:48 UTC, amtheshubham commented
> I did not make much changes. I don't know why is Appveyor Build is failing. Travis passed successfully and the app is also working fine.

I will try rectifying this issue on my machine and then will update here

2021-03-18 16:34 UTC, amtheshubham requested changes

2021-03-18 16:34 UTC, amtheshubham commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +        android:label="ProviderManagerDashboardActivity" />
@shivamsawlani02 add below two lines in place of line 61😄
```
android:label="activity_provider_management"
tools:layout="@layout/activity_provider_management" />
```

2021-03-18 18:06 UTC, shivamsawlani02 commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +        android:label="ProviderManagerDashboardActivity" />
Oh! 

> @shivamsawlani02 add following two lines in place of line 61
> 
> ```
> android:label="activity_provider_management"
> tools:layout="@layout/activity_provider_management" />
> ```

Oh! It was missing in the other two activities also. Didn't notice.

2021-03-18 18:10 UTC, amtheshubham commented on openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml
> +        android:label="ProviderManagerDashboardActivity" />
No. It's there. It's just that there's a procedure to follow in Navigation Component. You just changed the variable names.

2021-03-18 18:17 UTC, amtheshubham reviewed
@shivamsawlani02 I only asked you to change line 61. Please don't change other lines and please don't underestimate this.

2021-03-18 18:20 UTC, shivamsawlani02 commented
> @shivamsawlani02 I only asked you to change line 61. Please don't change other lines and please don't underestimate this.

But then won't the other activities be different?

2021-03-18 18:24 UTC, shivamsawlani02 commented
> @shivamsawlani02 I only asked you to change line 61. Please don't change other lines and please don't underestimate this.

Ok. Won't change.

2021-03-18 18:33 UTC, amtheshubham commented
@shivamsawlani02 The answer to your question is that the other two activities' names match with their layout files so no need of giving context to them. 
Moreover, It will compile but previous code is autogenerated by the system so I don't think you should mess with that code.

2021-03-18 18:49 UTC, shivamsawlani02 commented
> @shivamsawlani02 The answer to your question is that the other two activities' names match with their layout files so no need of giving context to them.
> Moreover, It will compile but previous code is autogenerated by the system so I don't think you should mess with that code.

@amtheshubham The app ran successfully on my mobile and now all the checks also passed and I think we should use the same naming convention in all the activities. If you wish I will change the code and remove context from the other two activities but since all checks passed I think it won't matter much and we can stick with this code.

2021-03-18 18:55 UTC, amtheshubham commented
> > @shivamsawlani02 The answer to your question is that the other two activities' names match with their layout files so no need of giving context to them.
> > Moreover, It will compile but previous code is autogenerated by the system so I don't think you should mess with that code.
> 
> @amtheshubham The app ran successfully on my mobile and now all the checks also passed and I think we should use the same naming convention in all the activities. If you wish I will change the code and remove context from the other two activities but since all checks passed I think it won't matter much and we can stick with this code.

They are redundant lines and not needed. Please remove them

2021-03-18 19:29 UTC, amtheshubham commented
LGTM!

2021-03-18 19:39 UTC, shivamsawlani02 commented
@rishabh-997 please review.

2021-03-18 19:42 UTC, amtheshubham approved these changes
LGTM!

2021-04-02 15:28 UTC, merged