Ac 889: Made improvements in the login page to correct many things not visible correctly in dark mode.
openmrs/openmrs-contrib-android-client pull request #872
Opened 2021-03-18 22:35 UTC by Akshatji800

## AC-889: Made changes in the login page UI to improve the visibility of different things in dark mode which are not clearly visible before.

## Description of what I changed

#### Made improvements in the hint text displayed in different text boxes to make them  accurately visible to the user in the dark mode.
#### Made improvement in he spinner button also to make the text displayed in the spinner box visible correctly to the user.
#### Made improvement to make the OpenMRS logo text "OpenMRS" visible correctly in he dark mode to the user.
#### Made improvement in the show/hide password eye type button to make it visible to the user in the dark mode also.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-889

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-03-19 10:01 UTC, shivamsawlani02 requested changes

2021-03-19 10:03 UTC, shivamsawlani02 commented
Attach the JIRA ticket ID to your commit message also.

2021-03-19 15:58 UTC, Akshatji800 commented
Resolved the suggested changes @shivamsawlani02

2021-03-20 17:37 UTC, LuGO0 requested changes
could you please attach screenshots before and after?

2021-03-20 17:37 UTC, LuGO0 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- No? Unsure? -> execute command `git pull --rebase upstream master` -->
un-necessary how is this related to this Issue?

2021-03-20 17:37 UTC, LuGO0 commented on openmrs-client/src/main/res/layout/spinner_item.xml
> +<TextView xmlns:android="http://schemas.android.com/apk/res/android"
license missing!!

2021-03-20 17:48 UTC, LuGO0 requested changes

2021-03-20 17:48 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
>          if (mLastCorrectURL.equals(ApplicationConstants.EMPTY_STRING)) {
you sure you dont want them in initViewField Method? because I dont see any preconditions for this setTextColor.

2021-03-20 17:48 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
similarly here !!

2021-03-20 18:19 UTC, Akshatji800 commented
![Screenshot_showing_improvements](https://user-images.githubusercontent.com/73401649/111881531-cbcabc00-89d6-11eb-9779-82ffe6e6668c.png)
BEFORE AND AFTER SCREENSHOT

2021-03-20 18:36 UTC, Akshatji800 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- No? Unsure? -> execute command `git pull --rebase upstream master` -->
I changed that by mistake unknowingly. I tried to revert back the changes, I reverted all of them also but then also it shows the change in one line un-necessarily even though there is no change made in that line.

2021-03-20 20:03 UTC, Akshatji800 commented on openmrs-client/src/main/res/layout/spinner_item.xml
> +<TextView xmlns:android="http://schemas.android.com/apk/res/android"
Added license @LuGO0

2021-03-20 20:05 UTC, Akshatji800 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
>          if (mLastCorrectURL.equals(ApplicationConstants.EMPTY_STRING)) {
Added those changes under initViewField Method as suggested by you @LuGO0

2021-03-20 20:09 UTC, Akshatji800 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
Added this also under the initViewField Method as suggested by you @LuGO0

2021-03-20 20:11 UTC, Akshatji800 commented
Thanks for all your precious suggestions @LuGO0 I have tried my best to resolve all of them you can once have a check again.

2021-03-21 03:44 UTC, LuGO0 commented
one more thing @Akshatji800 can we use styles here as they are central to the app, just curious if that can be used instead of directly using raw attributes? [this ](https://stackoverflow.com/questions/16694786/how-to-customize-a-spinner-in-android)might help

2021-03-21 17:59 UTC, Akshatji800 commented
No @LuGO0 I did nothing with the height of the textViews it appears so in the screenshot as the first one is emulator screenshot and the second one from my mobile device otherwise it is same in case of height as it was before.

2021-03-21 21:40 UTC, Akshatji800 commented
@rishabh-997 plz review

2021-05-05 04:33 UTC, LuGO0 requested changes

2021-05-05 04:33 UTC, LuGO0 commented on openmrs-client/src/main/res/layout/fragment_login.xml
>                      android:layout_height="wrap_content"
revert back we need to support lower level APIs, make it fill_parent again.

2021-05-05 04:34 UTC, LuGO0 commented
Please upload a final screenshot after making changes LGTM.

2021-05-05 10:50 UTC, Akshatji800 commented
@LuGO0 can you please review again. These are the screenshots showing the results of the changes made.
![image (13)](https://user-images.githubusercontent.com/73401649/117130449-b5799380-adbd-11eb-9ce9-317a499f5b4b.jpg)
![image (15)](https://user-images.githubusercontent.com/73401649/117130459-b8748400-adbd-11eb-9498-49a1fe44167b.jpg)

2021-05-05 13:36 UTC, Akshatji800 commented on openmrs-client/src/main/res/layout/fragment_login.xml
>                      android:layout_height="wrap_content"
reverted back @LuGO0

2021-08-19 15:39 UTC, merged