Migrating matchingpatients package to Kotlin & Viewbinding
openmrs/openmrs-contrib-android-client pull request #880
Opened 2021-03-23 11:46 UTC by SalahoAmro

## Description of what I changed

Migrated matchingpatients package to Kotlin & Viewbinding including:
- MatchingPatientsActivity
- MatchingPatientsContract
- MatchingPatientsFragment
- MatchingPatientsPresenter
- MergePatientsRecycleViewAdapter

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-952

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-03-23 14:12 UTC, shivamsawlani02 commented
@SalahoAmro please attach the JIRA Ticket ID to the commit message.

2021-03-23 14:31 UTC, SalahoAmro commented
@shivamsawlani02 Done, I've added it.

2021-03-23 14:37 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsPresenter.kt
> +import java.util.*
Avoid the use of star imports.

2021-03-23 14:37 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsFragment.kt
> +
Remove these 2 blank lines. Line 34 and 36.

2021-03-23 14:37 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsFragment.kt
> +
Remove this blank line too.

2021-03-23 14:42 UTC, shivamsawlani02 requested changes

2021-03-23 14:42 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsActivity.kt
> +        // Create fragment
Remove this comment

2021-03-23 14:42 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsActivity.kt
> +        // Create the presenter
Remove this comment

2021-03-23 14:42 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MergePatientsRecycleViewAdapter.kt
> +
Remove this line also

2021-03-23 14:42 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MergePatientsRecycleViewAdapter.kt
> +
Remove this also

2021-03-23 15:18 UTC, SalahoAmro commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsPresenter.kt
> +import java.util.*
Ok, changed it. I configured my IDE to the Java conventions, however, since this is a Kotlin file, it was not configured.

2021-03-23 15:19 UTC, SalahoAmro commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MergePatientsRecycleViewAdapter.kt
> +
Done all. Apologies for making a second commit. Should I remove the old one?

2021-03-23 17:43 UTC, shivamsawlani02 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MergePatientsRecycleViewAdapter.kt
> +
No. It's fine I guess

2021-03-23 17:45 UTC, shivamsawlani02 commented
LGTM!

2021-03-24 19:37 UTC, amtheshubham commented
I don't think you have added any tests still you have checked "I have added tests" box ?

2021-03-24 20:20 UTC, SalahoAmro commented
@amtheshubham Since it does not need tests, it is just refactoring the code. I was confused about whether to check it or not.
Unchecked now.

2021-05-04 15:17 UTC, LuGO0 approved these changes

2021-08-19 15:42 UTC, LuGO0 commented
@amrsalah3  Closing this for now. please open the PR again after fixing the merge conflicts. thanks

2021-08-19 15:42 UTC, closed without merging