AC-968/AC-969/AC-970: Fix Provider module offline support issues
openmrs/openmrs-contrib-android-client pull request #891
Opened 2021-04-10 08:00 UTC by SalahoAmro

## Description of what I changed

First, these 3 issues are related to each other and the same classes (and lines of code) need to be changed, so I've combined them in one PR for not producing merge conflicts.
1. Fixed provider's name being _[givenName givenName]_ instead of _[givenName familyName]_ in server when reconnecting to the internet. [AC-968]
2. Fixed AddProviderWorker being called forever even after success. [AC-969]
3. Fixed failing to edit or delete a newly created Provider in both online and offline modes. [AC-970]

## Issue I worked on

JIRA Issue:
https://issues.openmrs.org/browse/AC-968
https://issues.openmrs.org/browse/AC-969
https://issues.openmrs.org/browse/AC-970

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-04-10 10:02 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +				}
@SalahoAmro should we use either updateByUUID or updateById like we are updating uuid by id and then provider by uuid, can we simply update provider by id? will there be any Issues?

2021-04-10 10:08 UTC, LuGO0 commented
looks good to me I wanted to know more about the Id issue how did you get over it?

2021-04-11 16:52 UTC, SalahoAmro commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +
Done!

2021-04-11 17:14 UTC, SalahoAmro commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +				}
The method **updateProviderById()** searches for Provider by (_id_) field of Provider object, which is always empty always until we update it because the primary key of the provider is (__id_) field of its superclass _Resource_.
When we create a Provider object in AddProviderWorker using the data passed to the worker, the passed id is actually the __id_ NOT _id_. You can notice this in ProviderRepository in lines 140 and 146. So until now, _id_ field of this provider in the database table is empty. So we first, **updateProviderUuidById()** when connecting to the internet, then update rest of the data of the provider in the database using updateProviderById() which also updates the empty _id_ of the provider (not useful anyway because we already have __id_ value).

This is confusing, to be honest. IMO, Provider DAO methods should all be updated to use either _id or id, but first, we need to know what is actually the difference between them because _id is the primary key so we have to use it now.

2021-04-11 17:31 UTC, SalahoAmro commented
@LuGO0 I replied to your comment in the review about this. Also, I want to add that I tried running current tests in ProviderRoomDAOTest and they fail although Travis passes these tests! I mentioned that earlier here in Talk: https://talk.openmrs.org/t/gsoc-2021-openmrs-android-client-project-3-0-x-a-problem-with-testing/32786. So we can raise an issue if you kindly agree with me. Also, as I mentioned _id and id fields are really confusing and may be responsible for these tests failure, I tried my best to understand them and this PR is the only way to solve these issues without refactoring current Provider DAO methods that use _id_ field in all queries.

2021-04-13 12:18 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +				}
can we probe into this @SalahoAmro what are other entities using in this. I think we should draw a conclusion here and fix this problem, I am also confused by this for now.

2021-04-13 12:25 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +				}
This might help @SalahoAmro https://github.com/openmrs/openmrs-core/tree/master/api/src/main/java/org/openmrs

2021-04-14 15:44 UTC, SalahoAmro commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +				}
@LuGO0 I have already read the core data model and REST docs, _id is used in the server. We can notice this when fetching providers from the server for the first time, I inspected Android Client's database and found that _id fields are updated, whereas, id fields are empty.

2021-04-28 18:28 UTC, LuGO0 commented
I dont think we should merge this without understanding, will it be a huge change for us to start using _id instead of id because as I see in the openMRS models _id is used and id makes little sense to me atleast. sorry for the late reply

2021-04-28 22:25 UTC, SalahoAmro commented
> I dont think we should merge this without understanding, will it be a huge change for us to start using _id instead of id because as I see in the openMRS models _id is used and id makes little sense to me atleast. sorry for the late reply :(

I agree with you. We need to understand that first, but I wonder why doesn't anyone reply to us? :(

2021-06-20 14:00 UTC, LuGO0 commented
Hi @amrsalah3 were you able to figure out if there were really multiple providers added or just multiple API calls intercepted in chucker, i.e. was there an Issue with the chucker or something to do with offline functionality?

2021-06-20 14:31 UTC, amrsalah3 commented
@LuGO0 It was some problems with the offline structure, not chucker.

2021-06-20 14:41 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
>                  ToastUtil.success(OpenMRS.getInstance().getString(R.string.add_provider_success_msg));
Is it the Fix for the Issue we were facing @amrsalah3 the infinite calls?

2021-06-20 14:48 UTC, amrsalah3 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
>                  ToastUtil.success(OpenMRS.getInstance().getString(R.string.add_provider_success_msg));
Yes, asynchronous calls of the API were preventing the Success result from being returned from the the worker so it was retrying forever.
Now, I've replaced it with a synchronous call.

2021-06-20 14:51 UTC, amrsalah3 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
>                  ToastUtil.success(OpenMRS.getInstance().getString(R.string.add_provider_success_msg));
@LuGO0 check addProvider method, too. API call is modified inside it.

2021-06-20 14:56 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
>                  ToastUtil.success(OpenMRS.getInstance().getString(R.string.add_provider_success_msg));
perfect I was just trying this branch out locally.

2021-06-20 14:57 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/dao/ProviderRoomDAO.java
>      @Query("SELECT * FROM provider_table")
I will work a bit more here and experiment out a bit with _id and id Issue before

2021-06-20 14:59 UTC, amrsalah3 commented on openmrs-client/src/main/java/org/openmrs/mobile/dao/ProviderRoomDAO.java
>      @Query("SELECT * FROM provider_table")
Thank you!

2021-06-20 17:44 UTC, LuGO0 commented
Hi @amrsalah3 made some changes please review 😁

2021-06-20 17:56 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
I think this is wrong here the ID wont get setup in the db since its only for the response object

2021-06-20 18:06 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +
will do cleanup later.

2021-06-20 22:14 UTC, amrsalah3 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
> +                        response.body().setId(providerRoomDao.addProvider(response.body()));
What I understand now that there will be an auto-generated primary key __id_ and you deleted the obsolete _id_, so why you set the generated id to the response provider's object instead of just adding provider to Room?

2021-06-20 22:14 UTC, amrsalah3 commented on openmrs-client/src/main/java/org/openmrs/mobile/dao/ProviderRoomDAO.java
>      @Query("UPDATE provider_table SET uuid=:uuid WHERE _id=:id")
I think this method that I created is no longer needed.`updateProviderUuidById()`

2021-06-20 22:16 UTC, amrsalah3 commented
@LuGO0 Perfect work! :smiley:

2021-06-21 15:16 UTC, LuGO0 commented
Hi @rishabh-997 @amrsalah3 all 3 operations work fine for me now. could you please check once I have squashed all commits into 2 commits.

2021-06-21 19:52 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +            // Its necessary since server gives Error 500 if request has UUID set as ""
Can you remove this comment

2021-06-21 19:52 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
> +                    OpenMRS.getInstance().getOpenMRSLogger().e("Adding Provider Successful ");
Use string resource file

2021-06-21 19:53 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/UpdateProviderWorker.java
> +            // Its necessary since server gives Error 500 if request has UUID set as ""
Again, remove this

2021-06-21 19:53 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/UpdateProviderWorker.java
> +                    OpenMRS.getInstance().getOpenMRSLogger().e("Editing Provider Successful ");
String resource file

2021-06-21 19:55 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/models/Provider.kt
>  import com.google.gson.annotations.SerializedName
Can you remove star imports

2021-06-21 19:55 UTC, rishabh-997 requested changes
Rest LGTM. I'll just check the changes locally once

2021-06-21 20:01 UTC, LuGO0 commented
Yes @rishabh-997 I will make these changes please check once locally.

2021-06-22 19:45 UTC, LuGO0 commented
@rishabh-997 made required changes please review

2021-07-10 12:23 UTC, rishabh-997 approved these changes
LGTM... thanks for the efforts @LuGO0 @amrsalah3

2021-07-10 12:23 UTC, merged