AC-924 : Used ViewBinding in SyncedPatients package.
openmrs/openmrs-contrib-android-client pull request #903
Opened 2021-06-17 18:44 UTC by LuGO0

## Description of what I changed

1. Used ViewBinding in SyncedPatients package.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-924

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [ ] My pull request is **based on the latest changes** of the master branch.

2021-06-18 17:34 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
>      //Menu Items
Can you remove this comment too

2021-06-18 17:35 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsFragment.java
>      // Fragment components
Remove this

2021-06-18 17:35 UTC, rishabh-997 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsFragment.java
>      //Initialization Progress bar
This too. In fact remove all unnecessary comments

2021-06-18 17:36 UTC, rishabh-997 requested changes
Rest LGTM

2021-06-22 19:44 UTC, LuGO0 commented
@rishabh-997  made required changes please review.

2021-06-22 19:44 UTC, LuGO0 commented
@rishabh-997 made required changes please review

2021-06-25 09:24 UTC, merged