AC-988 : Add backslash in AddEditPatientFragment
openmrs/openmrs-contrib-android-client pull request #928
Opened 2021-10-29 09:59 UTC by rdodiya

## Description of what I changed

In Patient Registration, add backslash in DOB editText dynamically and  add 0 before date & month while selecting date from datepicker to maintain date format.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-988

## Test app after changes
![ac988](https://user-images.githubusercontent.com/75332758/139407577-8bc73668-2c21-4196-ac7f-73eec35e955c.jpg)

https://user-images.githubusercontent.com/75332758/139407879-8207b13f-4c39-417e-9352-aa59c9e903df.mp4

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2021-11-06 09:02 UTC, LuGO0 commented
can you post a previous Image as well just for history.

2021-11-06 20:09 UTC, rdodiya commented
> can you post a previous Image as well just for history. thanks !!

https://issues.openmrs.org/secure/attachment/60106/Screenshot_20210331-175757_OpenMRS_Android_Client%5B1%5D.jpg

2021-11-07 06:15 UTC, LuGO0 requested changes

2021-11-07 06:15 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
>              }
can you reformat the change?

2021-11-07 06:15 UTC, LuGO0 commented on openmrs-client/src/main/res/layout/fragment_patient_info.xml
>                              </com.google.android.material.textfield.TextInputLayout>
do we need a max length restriction?

2021-11-11 17:21 UTC, rdodiya commented
@LuGO0  Please inform if there is more to reformat in code.

2021-11-13 04:15 UTC, LuGO0 commented
can you squash these changes @rdodiya ?

2021-11-16 09:27 UTC, rdodiya commented
I am creating new PR ,there is some problem i am faced after squashed the commit

2021-11-16 09:27 UTC, closed without merging