AC-994 Migrate AllergyRoomDao To Kotlin
openmrs/openmrs-contrib-android-client pull request #933
Opened 2022-01-16 10:37 UTC by Rohit-2602

## Description of what I changed
Migrate AllergyRoomDao To Kotlin

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-994

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2022-01-16 20:45 UTC, HerbertYiga commented
thanks @Rohit-2602  you have some breaking tests for this checkout your CI logs

2022-01-17 05:24 UTC, Rohit-2602 commented
@LuGO0 and @HerbertYiga I have to change TypeConvertor because without changes it was causing tests to fail with the message
```xml
gson.fromJson(value, listType) must not be null
```

2022-01-17 16:47 UTC, LuGO0 requested changes

2022-01-17 16:47 UTC, LuGO0 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/AllergyRoomDAO.kt
> +import androidx.room.Update
why these changes?

2022-01-17 16:48 UTC, LuGO0 commented
Some minor changes, commit messages should be `AC-XXX : description` .
I will run it once locally and then merge it post the requested changes are done LGTM !

2022-01-17 16:52 UTC, Rohit-2602 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/AllergyRoomDAO.kt
> +import androidx.room.Update
it is just because of code reformation and semi-colon changes.

2022-01-18 16:59 UTC, LuGO0 commented
> Some minor changes, commit messages should be `AC-XXX : description` . I will run it once locally and then merge it post the requested changes are done LGTM !

please reword your commit and force push.

2022-01-18 17:49 UTC, Rohit-2602 commented
@LuGO0 done

2022-01-29 17:50 UTC, merged