AC-1020: Add Test For PatientMerger
openmrs/openmrs-contrib-android-client pull request #943
Opened 2022-02-10 18:49 UTC by Rohit-2602

## Description of what I changed
Add Test case for PatientMerger
Contains 2 test case - 
- Patient Fields not null or "null"
- Some Patient Fields are null or "null"

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-1020

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2022-02-10 19:19 UTC, Rohit-2602 commented
@LuGO0 Please review

2022-02-11 18:45 UTC, LuGO0 requested changes

2022-02-11 18:45 UTC, LuGO0 commented on openmrs-client/src/test/java/org/openmrs/mobile/utilities/PatientMergerTest.kt
> +    fun `non null fields remain same and null fields changes after merge`() {
@Rohit-2602 pick up the testing conventions from the already written tests and then refractor these tests to abide by those conventions.

2022-02-12 07:36 UTC, Rohit-2602 commented
@LuGO0 This is the naming convention for Kotlin test cases.
More here - https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods.
This makes the test case more readable.

2022-02-13 05:10 UTC, LuGO0 commented
> @LuGO0 This is the naming convention for Kotlin test cases. More here - https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods. This makes the test case more readable.

Lets use the second option mentioned there dont want to have multiple different conventions in the codebase `ensureEverythingWorks_onAndroid()`

2022-02-14 16:41 UTC, merged