AC-992: Improved Dark Mode
openmrs/openmrs-contrib-android-client pull request #944
Opened 2022-02-27 06:55 UTC by prateek27das

AC-992 : Improved Dark Mode

## Description of what I changed
 In Dark mode, theme of custom dialog is light which is straining to eyes in dark.
 I Changed it to dark theme.

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-992

## Short Video demonstrating my work
https://drive.google.com/file/d/183Wy5PNdKAqUI5Titx3w2LAtunwWMfNf/view?usp=sharing

## Screenshot after the improvement 
<img width="250" alt="Logging out" src="https://user-images.githubusercontent.com/77295322/155871776-940b34e8-9e61-4636-8ac2-f5a3cc58b389.png"> <img width="250" alt="Select Location" src="https://user-images.githubusercontent.com/77295322/155871780-42eb9ad1-f350-4df5-817c-3f0a7dd1d651.png">

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2022-02-27 07:10 UTC, prateek27das commented
hi @LuGO0 can you please review now ?

2022-02-28 16:57 UTC, LuGO0 commented
Sure eill review !

2022-03-01 17:59 UTC, LuGO0 requested changes
try getting the openmrsFormatter before making any formatting changes it would be easy for you to maintain the correct formatting.
other things LGTM !

2022-03-01 17:59 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
> +                            .hideURLDialog();
remove these formatting changes. only format portions of the code you changed.

2022-03-01 17:59 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
> +                OpenMRS.getInstance().getResources().getDisplayMetrics());
ditto

2022-03-01 17:59 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
> +                OpenMRS.getInstance().getResources().getDisplayMetrics());
ditto

2022-03-01 17:59 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
> +                            .login(true);
ditto

2022-03-01 17:59 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
> +                            .getSupportFragmentManager()
ditto

2022-03-01 17:59 UTC, LuGO0 commented on openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
> +                R.layout.row_single_checked_layout, locationList));
ditto

2022-03-01 17:59 UTC, LuGO0 commented on openmrs-client/src/main/res/layout/openmrs_text_view_field.xml
> +        >
wrong formatting this should be in above line?

2022-03-01 17:59 UTC, LuGO0 commented on openmrs-client/src/main/res/layout/openmrs_text_view_field.xml
> +            />
similar issue.

2022-03-02 12:02 UTC, prateek27das commented
@LuGO0 I tried to import the OpenMRS Formatter using Eclipse Code Formatter. I followed the "Contribution GuideLines". But the formatter is not coming to the Scheme Portion. 

I am facing the same issue as it was discussed before in OpenMRS talk 
here is the link of that talk - https://talk.openmrs.org/t/how-to-import-openmrsformatter-xml-in-android-studio/31549

Please help me to set the OpenMRS Formatter !!!

This is my Eclipse Code Formatter settings


<img width="450" alt="Screenshot 2022-03-02 at 5 22 41 PM" src="https://user-images.githubusercontent.com/77295322/156357118-72335643-1a67-4427-8de2-0bbddebd7153.png">

2022-03-02 16:14 UTC, LuGO0 commented
I think you just need to install the eclipse code formatter plugin which helps in this, not really sure about the whole process since haven't done it in a while, just try it with the plugin if you are not able to do it, I will try to lay down some elaborate steps for the same.

2022-03-02 17:03 UTC, prateek27das commented
@LuGO0 ,I have installed the Eclipse Code formatter plugin and do the required as described in the "Contribution GuideLines"

2022-03-02 18:39 UTC, LuGO0 commented
![Screenshot 2022-03-03 000809](https://user-images.githubusercontent.com/30355336/156426622-f2089fa2-6de4-41c8-a588-ed5df2071b82.png)
I did it using this settings button and imported the style using the openmrsformatter
 XML file

2022-03-02 18:41 UTC, LuGO0 commented
try this out https://github.com/krasa/EclipseCodeFormatter#instructions

2022-03-02 18:41 UTC, LuGO0 commented
For this PR you can just revert those changes manually so that I can merge them.

2022-03-03 09:00 UTC, prateek27das commented
I am setting up the formatter  
As you said earlier ,I reverted those changes manually. for the  CustomFragmentDialog.java as of now. 

can you guide me formatting the "openmrs_text_view_field.xml" manually.

2022-03-05 08:03 UTC, merged