AC-1077: Add/Enhance Observation APIs
openmrs/openmrs-contrib-android-client pull request #997
Opened 2023-06-06 18:21 UTC by shubhamsgit

## Description of what I changed

- This PR is for the enhancement of the Observation APIs in the SDK

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-1077

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2023-06-18 09:11 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/EncounterRepository.kt
> +import com.openmrs.android_sdk.library.models.*
Avoid star imports

2023-06-18 09:13 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ObservationRepository.kt
> +    fun createObservationFromLocal(observationEntity: ObservationEntity): Observable<Observation>{
```suggestion
    fun createObservationFromLocal(observationEntity: ObservationEntity): Observable<Observation> {
```

2023-06-18 09:13 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ObservationRepository.kt
> +        return AppDatabaseHelper.createObservableIO(Callable{
```suggestion
        return AppDatabaseHelper.createObservableIO(Callable {
```

2023-06-18 09:15 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ObservationRepository.kt
> +            if (!NetworkUtils.isOnline()) throw Exception("Must be online to fetch observations")
```suggestion
            if (!NetworkUtils.isOnline()) throw Exception("To retrieve observations, an internet connection is required.")
```

2023-06-18 09:15 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ObservationRepository.kt
> +        return AppDatabaseHelper.createObservableIO(Callable{
```suggestion
        return AppDatabaseHelper.createObservableIO(Callable {
```

2023-06-18 09:16 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ObservationRepository.kt
> +                if (isSuccessful && body() != null) {
```suggestion
            if (!NetworkUtils.isOnline()) throw Exception("To retrieve observations, an internet connection is required.")

            restApi.getObservationByUuid(uuid).execute().run {
                if (isSuccessful && body() != null) {
```

2023-06-18 09:16 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ObservationRepository.kt
> +            if (!NetworkUtils.isOnline()) throw Exception("Must be online to fetch observations")
same

2023-06-18 09:18 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/ObservationDAO.java
> +        return id;
```suggestion
        return observationRoomDAO.addObservation(observationEntity);
```

2023-06-18 09:19 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/ObservationDAO.java
> +        return count;
```suggestion
        return observationRoomDAO.updateObservation(observationEntity);
```

2023-06-18 09:19 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/ObservationDAO.java
> +        return id;
type convert and return without storing it..

2023-06-18 09:19 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/ObservationRoomDAO.kt
> +import androidx.room.*
star imports

2023-06-18 09:21 UTC, rishabh-997 commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
> +        val standaloneObservationEntity = StandaloneObservationEntity(
```suggestion
        return StandaloneObservationEntity(
```

2023-06-18 09:22 UTC, rishabh-997 requested changes
Looks good

2023-06-18 18:38 UTC, shubhamsgit commented on openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/EncounterRepository.kt
> +import com.openmrs.android_sdk.library.models.*
My bad :( Done!

2023-06-26 15:52 UTC, rishabh-997 commented
New changes look good. Thanks

2023-06-26 15:53 UTC, merged