AC-1079: Add/Enhance Visit APIs in SDK
openmrs/openmrs-contrib-android-client pull request #999
Opened 2023-06-13 18:49 UTC by shubhamsgit

## Description of what I changed

- This is a subtask of enhancing the android sdk by incorporating more functionalities for Visit endpoint.
- These functions will be beneficial for the filtering features used by the implementers. 

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-1079

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2023-06-18 19:08 UTC, shubhamsgit commented
@rishabh-997 I will resolve the conflicts after the merge of AC-1077. Otherwise more conflicts will occur.

2023-06-26 16:02 UTC, rishabh-997 requested changes

2023-07-13 21:33 UTC, shubhamsgit commented
@rishabh-997 Since this branch had too many conflicts and small number of files, I have created another branch for this issue which is based on the latest master. Please check😄

2023-07-13 21:33 UTC, shubhamsgit commented
Created new branch for the issue.

2023-07-13 21:33 UTC, closed without merging